"""Unmanual migration

Revision ID: 00f20e06022a
Revises: 65e38acb25ea
Create Date: 2026-06-01 21:35:22.528179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f20e06022a'
down_revision: Union[str, Sequence[str], None] = '65e38acb25ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('hour', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('minute', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'minute')
    op.drop_column('tasks', 'hour')
    # ### end Alembic commands ###
