"""Unmanual migration

Revision ID: 01a9d5df2e12
Revises: 89bea03a3505
Create Date: 2026-06-03 19:58:27.101302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01a9d5df2e12'
down_revision: Union[str, Sequence[str], None] = '89bea03a3505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekends',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekends_id'), 'weekends', ['id'], unique=False)
    op.drop_index(op.f('ix_Weekend_id'), table_name='Weekend')
    op.drop_table('Weekend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Weekend',
    sa.Column('master_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], name=op.f('Weekend_master_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Weekend_pkey'))
    )
    op.create_index(op.f('ix_Weekend_id'), 'Weekend', ['id'], unique=False)
    op.drop_index(op.f('ix_weekends_id'), table_name='weekends')
    op.drop_table('weekends')
    # ### end Alembic commands ###
