"""Unmanual migration

Revision ID: 12e4fa99c8ec
Revises: 00f20e06022a
Create Date: 2026-06-01 21:58:30.575669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e4fa99c8ec'
down_revision: Union[str, Sequence[str], None] = '00f20e06022a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'day_month_year')
    op.drop_column('tasks', 'hour')
    op.drop_column('tasks', 'minute')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('minute', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('day_month_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'datetime')
    # ### end Alembic commands ###
