"""Unmanual migration

Revision ID: 6264f76895f1
Revises: 31671b633b9d
Create Date: 2026-06-09 13:04:37.905068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6264f76895f1'
down_revision: Union[str, Sequence[str], None] = '31671b633b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
