"""Unmanual migration

Revision ID: 7c435fa1b403
Revises: 01a9d5df2e12
Create Date: 2026-06-03 21:14:13.635224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c435fa1b403'
down_revision: Union[str, Sequence[str], None] = '01a9d5df2e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'weekends', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weekends', type_='unique')
    # ### end Alembic commands ###
