"""Unmanual migration

Revision ID: 7e978f282048
Revises: a67941a75a02
Create Date: 2026-06-01 22:56:49.653172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e978f282048'
down_revision: Union[str, Sequence[str], None] = 'a67941a75a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('dateTime', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('tasks', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'dateTime')
    # ### end Alembic commands ###
