"""Unmanual migration

Revision ID: a186739e13c9
Revises: 7c435fa1b403
Create Date: 2026-06-05 12:11:24.559181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a186739e13c9'
down_revision: Union[str, Sequence[str], None] = '7c435fa1b403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fio')
    # ### end Alembic commands ###
