"""Unmanual migration

Revision ID: b9086b52adc7
Revises: 6264f76895f1
Create Date: 2026-06-09 13:10:02.258876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9086b52adc7'
down_revision: Union[str, Sequence[str], None] = '6264f76895f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'FIO',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'FIO',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
