"""Unmanual migration

Revision ID: fdbc0e3acc1d
Revises: b9086b52adc7
Create Date: 2026-06-09 13:17:20.413201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbc0e3acc1d'
down_revision: Union[str, Sequence[str], None] = 'b9086b52adc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'FIO',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'FIO',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
